#!/usr/bin/env node
'use strict';
// impeccable-run-log.js — PostToolUse(Skill) — automatically logs every impeccable invocation (which
// command, on what target/dashboard, when) so Douglas can check what's been run on a given app without
// having to remember or re-derive it from chat history.
//
// Added 2026-07-04 with Douglas's explicit go-ahead (a general "make something automatic" request alone
// doesn't authorize a new hook -- this needed a direct confirmation, which he gave).
//
// Why a hook and not a promise to remember: per CLAUDE.md's "make the fix real" rule, "I'll log it" isn't
// a durable fix. This fires automatically on every `Skill` tool call, no matter which session or agent
// invokes it, and needs no cooperation from the invoking turn.
//
// Detection-only: never blocks, never modifies the invocation. Writes two things per project (the cwd at
// invocation time -- matches where impeccable's own critique-storage.mjs already writes `.impeccable/critique/`,
// so this log sits alongside it):
//   <cwd>/.impeccable/run_log.jsonl   -- one JSON record per invocation, append-only, machine-readable
//   <cwd>/.impeccable/RUN_LOG.md      -- regenerated from the JSONL on every run, grouped by target -- the
//                                         human-readable surface Douglas actually reads
//
// Known limitation: only captures invocations that go through the `Skill` tool. Work done by hand-following
// a reference doc (Read-ing reference/<command>.md and executing it without a fresh Skill call) is invisible
// to this hook -- exactly what happened once already this session (critique's two assessments were dispatched
// via Agent with the procedure inline, not via a second Skill call). Such sessions need a manual backfill entry
// (source:"manual-entry" in the JSONL) to stay honest about what the hook actually saw vs. what a human added.
const fs = require('fs');
const path = require('path');
const S = require(path.join(__dirname, 'hook-state.js'));

const KNOWN_COMMANDS = [
  'craft', 'shape', 'init', 'document', 'extract', 'critique', 'audit', 'polish', 'bolder', 'quieter',
  'distill', 'harden', 'onboard', 'animate', 'colorize', 'typeset', 'layout', 'delight', 'overdrive',
  'clarify', 'adapt', 'optimize', 'live', 'pin', 'unpin', 'hooks',
];

function parseCommandAndTarget(args) {
  const s = String(args || '').trim();
  if (!s) return { command: 'menu', target: null };
  const firstWord = s.split(/\s+/)[0].replace(/[:,]$/, '').toLowerCase();
  if (KNOWN_COMMANDS.includes(firstWord)) {
    return { command: firstWord, target: s.slice(firstWord.length).trim() || null };
  }
  // no recognized command as the first word -- this is either a no-arg-style routing ask (a target
  // description with no command) or free-form intent text; either way impeccable's own routing decides,
  // so log it as 'menu' (matches "No argument: the user is asking what should I do" in impeccable's own
  // routing rules) with the whole string as context.
  return { command: 'menu', target: s.slice(0, 200) };
}

// Best-effort "which dashboard/app" grouping key, tried in order: (1) a quoted .html/.py filename, (2) the
// last path segment after a / or \ (handles a full disk path mentioned in prose -- the common real case,
// e.g. "...\AI for CAD\html\Interface Extractor Viewer.html, generated by..."), (3) a bounded run of up to
// 4 preceding words + the filename (for a bare, unquoted, no-path mention), (4) first ~60 chars as a last
// resort. (3) can still over-capture one preceding word in an unquoted, path-less, prose-only mention
// (e.g. "cad-forge Interface Extractor Viewer.html" with no quotes/path/comma) -- a known limitation of a
// best-effort grouping key, not meant to be exact; quoting the filename or giving a full path avoids it.
function extractDashboardKey(target) {
  if (!target) return '(unspecified target)';
  const quoted = target.match(/["']([^"'/\\]+\.(?:html|py))["']/i);
  if (quoted) return quoted[1].trim();
  const pathLike = target.match(/[\\/]([A-Za-z0-9 _-]+\.(?:html|py))/i);
  if (pathLike) return pathLike[1].trim();
  const bounded = target.match(/(?:^|[\s(])((?:[A-Za-z0-9_-]+[ ]){0,4}[A-Za-z0-9_-]+\.(?:html|py))/i);
  if (bounded) return bounded[1].trim();
  return target.slice(0, 60).trim();
}

function loadRecords(jsonlPath) {
  if (!S.exists(jsonlPath)) return [];
  return fs.readFileSync(jsonlPath, 'utf8').split('\n').filter(Boolean).map(l => {
    try { return JSON.parse(l); } catch (_) { return null; }
  }).filter(Boolean);
}

function renderMarkdown(records) {
  const byTarget = new Map();
  records.forEach(r => {
    const key = r.dashboard || '(unspecified target)';
    if (!byTarget.has(key)) byTarget.set(key, []);
    byTarget.get(key).push(r);
  });
  const lines = [
    '# Impeccable run log',
    '',
    'Auto-generated by `impeccable-run-log.js` on every `/impeccable` invocation -- do not hand-edit, it is',
    'overwritten on the next run. Rows marked `manual-entry` were backfilled by hand for work done before this',
    'hook existed, or work executed by following a reference doc directly rather than a fresh Skill call.',
    '',
  ];
  [...byTarget.entries()].sort((a, b) => a[0].localeCompare(b[0])).forEach(([target, recs]) => {
    lines.push('## ' + target, '', '| When | Command | Source | Notes |', '|---|---|---|---|');
    recs.sort((a, b) => (a.ts || '').localeCompare(b.ts || '')).forEach(r => {
      lines.push('| ' + (r.ts || '?') + ' | ' + (r.command || '?') + ' | ' + (r.source || 'skill-tool') + ' | ' +
        (r.notes || '').replace(/\|/g, '\\|') + ' |');
    });
    lines.push('');
  });
  return lines.join('\n');
}

function logInvocation(cwd, record) {
  const dir = S.norm(cwd) + '/.impeccable';
  if (!S.ensureDir(dir)) return;
  const jsonlPath = dir + '/run_log.jsonl';
  try { fs.appendFileSync(jsonlPath, JSON.stringify(record) + '\n'); } catch (_) { return; }
  try {
    const records = loadRecords(jsonlPath);
    fs.writeFileSync(dir + '/RUN_LOG.md', renderMarkdown(records));
  } catch (_) { /* jsonl append already succeeded; markdown regen is best-effort */ }
}

function main() {
  const input = S.readStdin();
  const toolInput = input.tool_input || {};
  const skillName = String(toolInput.skill || '');
  if (!/^impeccable(:|$)/i.test(skillName)) return;   // not an impeccable invocation

  const { command, target } = parseCommandAndTarget(toolInput.args);
  const record = {
    ts: new Date().toISOString(),
    sid: S.sid(input),
    command,
    target: target || null,
    dashboard: extractDashboardKey(target),
    source: 'skill-tool',
  };
  logInvocation(S.cwdOf(input), record);
}

if (require.main === module) {
  try { main(); } catch (_) { /* detection-only: never throw, never block */ }
}

module.exports = { parseCommandAndTarget, extractDashboardKey, renderMarkdown, loadRecords };
